### PR TITLE
Add ruby-version file

### PR DESCRIPTION
**Pull request by martijnbleeker**

### CODE REVIEW

**Comment by wvengen** [comment]
I don't think this is needed - Github doesn't allow running arbitrary Ruby here, and provides its own infrastructure for running Jekyll. I don't think a specific Ruby version is relevant here.
What would be a reason for inclusion?

**Comment by martijnbleeker** [comment]
It failed to bundle on my local machine (`json` 💢), because my profile has ruby 2.4 as default. 
So in this case, it's mainly to switch automatically to the correct ruby on the development machine.

**Comment by wvengen** [comment]
Would `2.3` be more flexible, or is `2.3.3` needed?

**Comment by martijnbleeker** [comment]
I think `2.3` is fine. I recall an issue I had with specifying a less strict version, but I don't know what the problem was anymore.

**Comment by wvengen** [comment]
Thanks!

**Pull request merged**
