### PR TITLE
Add usage_ids filter option documentation

### PR DESCRIPTION
**Pull request by martijnbleeker**

### CODE REVIEW

**Review by wvengen — APPROVED** [review]

**Comment by wvengen** [comment]
Merge when deployed to production, right?

**Comment by martijnbleeker** [comment]
I think so, maybe we want to merge it sooner to keep the documentation up to date for @madhums

**Comment by wvengen** [comment]
@martijnbleeker this also describes the public API, which I'd like to give priority. @madhums can also look at the discussion in issues right now. If we want different production and staging documentation, I propose to add the swagger file to the api repository, then we always have it up-to-date with the version deployed.

**Comment by martijnbleeker** [comment]
Ok, sounds fair. Maybe we could add that information to the README as well.
I see the `total` count documentation was added 5 days ago. While the actual feature has been merged 1 day ago (not deployed yet)

**Comment by wvengen** [comment]
Hah, well found ;)

**Pull request merged**
